linters-settings:
  errcheck:
    ignore: |
       github.com/hashicorp/terraform-plugin-sdk/helper/schema:ForceNew|Set
      fmt:.*
      io:Close
      github.com/hashicorp/terraform-provider-google-beta/google-beta:Set
      encoding/json:Unmarshal
      net/http:Request.ParseForm
      github.com/hashicorp/terraform-plugin-sdk/helper/schema:Set
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus
  misspell:
    locale: US
  lll:
    # Default is 120. '\t' is counted as 1 character.
    # set our project to 200, as things like v3_structs with inline comments end up being a touch long
    # also, for anyone using vscode, use the following configs:
    # "rewrap.wrappingColumn": 200 ... requires the rewrap plugin
    # "editor.rulers": [200]
    line-length: 500
  gocritic:
    disable:
      - ifElseChain
  forbidigo:
    ignore-tests: true
    exclude:
      - '^fmt\.Print(|f|ln)$'
  tagliatelle:
    case:
      json: snake

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - vet

issues:
  exclude:
    - composite literal uses unkeyed fields
  exclude-rules:
    - path: _test\.go
      linters:
        - testpackage
      # part of the golangci govet package is picking up things that go vet doesn't. Seems flaky, shutting that specific error off
    - path: client/client.go
      linters:
        - interfacer
      # interfacer lint on `filter` func suggests lint changes that dont compile
      # Details: linter suggests to convert `body` param to io.Reader since we don't use Close method, but return type requires
      ## io.ReadCloser thus failing to compile

run:
  # which dirs to skip: they won't be analyzed;
  skip-dirs:
    - vendor
    - future
    - nutanix/sdks/v3
