/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// How and where to backup the kind
type BackupPolicy struct {

	// Consistency group to which this entity belongs to
	ConsistencyGroupUuid string `json:"consistency_group_uuid,omitempty" bson:"consistency_group_uuid,omitempty"`

	// Replication targets
	ReplicationTargets []BackupPolicyReplicationTargets `json:"replication_targets,omitempty" bson:"replication_targets,omitempty"`

	// Snapshot application consistency property
	SnapshotType string `json:"snapshot_type,omitempty" bson:"snapshot_type,omitempty"`
}
