/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

type BackupPolicySnapshotSchedules struct {

	// Local retention quantity
	LocalRetentionQuantity int64 `json:"local_retention_quantity,omitempty" bson:"local_retention_quantity,omitempty"`

	// Remote retention quantity
	RemoteRetentionQuantity int64 `json:"remote_retention_quantity,omitempty" bson:"remote_retention_quantity,omitempty"`

	Schedule SnapshotSchedule `json:"schedule,omitempty" bson:"schedule,omitempty"`
}
