/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Customer information used in Certificate Signing Request for creating digital certificates.
type CertificationSigningInfo struct {

	// The Town or City where customer's business is located.
	City string `json:"city,omitempty" bson:"city,omitempty"`

	// Common name of the organization or host server
	CommonName string `json:"common_name,omitempty" bson:"common_name,omitempty"`

	// Common name is by default <node_uuid>.nutanix.com, but if a customer wants something instead of nutanix.com they can specify it here.
	CommonNameSuffix string `json:"common_name_suffix,omitempty" bson:"common_name_suffix,omitempty"`

	// Two-letter ISO code for Country where customer's organization is located.
	CountryCode string `json:"country_code,omitempty" bson:"country_code,omitempty"`

	// Email address of the certificate administrator.
	EmailAddress string `json:"email_address,omitempty" bson:"email_address,omitempty"`

	// Name of the customer business.
	Organization string `json:"organization,omitempty" bson:"organization,omitempty"`

	// The Province, Region, County or State where customer business is is located.
	State string `json:"state,omitempty" bson:"state,omitempty"`
}
