/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// The regions that have changed in the right half-open interval: [start_offset, next_offset).
type ChangedRegions struct {

	// Size of the file specified by snapshot_file_path
	FileSize int64 `json:"file_size,omitempty" bson:"file_size,omitempty"`

	// The offset from where the client must continue the request. This field will not be set when there are no more changed regions to be returned. Note that the next_offset can be outside the endOffset specified by the client in the request. This helps clients reach the next changed offset faster.
	NextOffset int64 `json:"next_offset,omitempty" bson:"next_offset,omitempty"`

	// List of regions describing the change for the interval [start_offset, next_offset].
	RegionList []Region `json:"region_list,omitempty" bson:"region_list,omitempty"`
}
