/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Cloud credentials resources
type CloudCredentialsResources struct {

	// Cloud site type
	CloudType string `json:"cloud_type,omitempty" bson:"cloud_type,omitempty"`

	// Indicates if it is the default credentials
	IsDefault bool `json:"is_default,omitempty" bson:"is_default,omitempty"`

	// Access key for AWS, or subscription id for Azure
	KeyId string `json:"key_id,omitempty" bson:"key_id,omitempty"`

	// Secret key for AWS, or full file path of the Azure client certificate file(<file_name>.pem)
	SecureId string `json:"secure_id,omitempty" bson:"secure_id,omitempty"`
}
