/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Cluster network.
type ClusterNetwork struct {
	DomainServer ClusterDomainServer `json:"domain_server,omitempty" bson:"domain_server,omitempty"`

	// The cluster IP address that provides external entities access to various cluster data services.
	ExternalDataServicesIp string `json:"external_data_services_ip,omitempty" bson:"external_data_services_ip,omitempty"`

	// The local IP of cluster visible externally.
	ExternalIp string `json:"external_ip,omitempty" bson:"external_ip,omitempty"`

	// External subnet for cross server communication. The format is IP/netmask.
	ExternalSubnet string `json:"external_subnet,omitempty" bson:"external_subnet,omitempty"`

	// List of proxies to connect to the service centers.
	HttpProxyList []ClusterNetworkEntity `json:"http_proxy_list,omitempty" bson:"http_proxy_list,omitempty"`

	// List of HTTP proxy whitelist.
	HttpProxyWhitelist []HttpProxyWhitelist `json:"http_proxy_whitelist,omitempty" bson:"http_proxy_whitelist,omitempty"`

	// The internal subnet is local to every server - its not visible outside.iSCSI requests generated internally within the appliance (by user VMs or VMFS) are sent to the internal subnet. The format is IP/netmask.
	InternalSubnet string `json:"internal_subnet,omitempty" bson:"internal_subnet,omitempty"`

	// The list of IP addresses of the name servers.
	NameServerIpList []string `json:"name_server_ip_list,omitempty" bson:"name_server_ip_list,omitempty"`

	// Comma separated list of subnets (of the form 'a.b.c.d/l.m.n.o') that are allowed to send NFS requests to this container. If not specified, the global NFS whitelist will be looked up for access permission. The internal subnet is always automatically considered part of the whitelist, even if the field below does not explicitly specify it. Similarly, all the hypervisor IPs are considered part of the whitelist. Finally, to permit debugging, all of the SVMs local IPs are considered to be implicitly part of the whitelist.
	NfsSubnetWhitelist []string `json:"nfs_subnet_whitelist,omitempty" bson:"nfs_subnet_whitelist,omitempty"`

	// The list of IP addresses or FQDNs of the NTP servers.
	NtpServerIpList []string `json:"ntp_server_ip_list,omitempty" bson:"ntp_server_ip_list,omitempty"`

	SmtpServer SmtpServer `json:"smtp_server,omitempty" bson:"smtp_server,omitempty"`
}
