/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Cluster domain server. Only applied to the cluster with all Hyper-V hosts.
type ClusterDomainServer struct {
	DomainCredentials Credentials `json:"domain_credentials,omitempty" bson:"domain_credentials,omitempty"`

	// Joined domain name. In 'put' request, empty name will unjoin the cluster from current domain.
	Name string `json:"name,omitempty" bson:"name,omitempty"`

	// The IP of the nameserver that can resolve the domain name. Must set when joining the domain.
	Nameserver string `json:"nameserver,omitempty" bson:"nameserver,omitempty"`
}
