/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Container Resources Definition.
type ContainerResources struct {

	// Various options for container.
	ContainerOptions ContainerOptions `json:"container_options,omitempty" bson:"container_options,omitempty"`

	// Desired state of the container.
	ContainerState string `json:"container_state,omitempty" bson:"container_state,omitempty"`

	// Image name to be used for container.
	ImageName string `json:"image_name,omitempty" bson:"image_name,omitempty"`

	// Reference to container registry.
	RegistryReference DockerRegistryReference `json:"registry_reference,omitempty" bson:"registry_reference,omitempty"`

	// Networks associated with this container.
	SubnetReferenceList []SubnetReference `json:"subnet_reference_list,omitempty" bson:"subnet_reference_list,omitempty"`

	// Volumes associated with this container.
	VolumeList []VolumeGroup `json:"volume_list,omitempty" bson:"volume_list,omitempty"`

	// Referenced volumes associated with this container.
	VolumeReferenceList []VolumeGroupReference `json:"volume_reference_list,omitempty" bson:"volume_reference_list,omitempty"`
}
