/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Spec for defining DHCP options.
type DhcpOptions struct {
	BootFileName string `json:"boot_file_name,omitempty" bson:"boot_file_name,omitempty"`

	DomainName string `json:"domain_name,omitempty" bson:"domain_name,omitempty"`

	DomainNameServers string `json:"domain_name_servers,omitempty" bson:"domain_name_servers,omitempty"`

	DomainSearch string `json:"domain_search,omitempty" bson:"domain_search,omitempty"`

	TftpServerName string `json:"tftp_server_name,omitempty" bson:"tftp_server_name,omitempty"`
}
