/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// The parameters to search for directory service.
type DirectoryServiceSearchMetadata struct {

	// The search string.
	Query string `json:"query,omitempty" bson:"query,omitempty"`

	// The attributes the search operation returns. If not available, a list of default attributes is returned.
	ReturnedAttributeList []string `json:"returned_attribute_list,omitempty" bson:"returned_attribute_list,omitempty"`

	// The attributes for search operation. If not specified, search is performed with the common name.
	SearchedAttributeList []string `json:"searched_attribute_list,omitempty" bson:"searched_attribute_list,omitempty"`
}
