/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// The details of the directory service.
type DirectoryServiceResources struct {

	// List of distinguished names of the admin group in the directory service.
	AdminGroupList []string `json:"admin_group_list,omitempty" bson:"admin_group_list,omitempty"`

	// The list of admin users available in the directory service.
	AdminUserReferenceList []UserReference `json:"admin_user_reference_list,omitempty" bson:"admin_user_reference_list,omitempty"`

	// Type of the directory service.
	DirectoryType string `json:"directory_type,omitempty" bson:"directory_type,omitempty"`

	// The domain name of the directory service.
	DomainName string `json:"domain_name,omitempty" bson:"domain_name,omitempty"`

	ServiceAccount ServiceAccount `json:"service_account,omitempty" bson:"service_account,omitempty"`

	// URL of the directory.
	Url string `json:"url,omitempty" bson:"url,omitempty"`
}
