/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Docker registry resources
type DockerRegistryResources struct {

	// Certificate required for the private docker registry
	Certificate string `json:"certificate,omitempty" bson:"certificate,omitempty"`

	// Flag to indicate whether the docker registry is enabled or not. If unset, defaults to False.
	IsEnabled bool `json:"is_enabled,omitempty" bson:"is_enabled,omitempty"`

	// Flag to indicate whether the docker registry is a system default
	IsSystemDefault bool `json:"is_system_default,omitempty" bson:"is_system_default,omitempty"`

	// Password of the user for the docker registry
	Password string `json:"password,omitempty" bson:"password,omitempty"`

	// URL of the docker registry
	Url string `json:"url,omitempty" bson:"url,omitempty"`

	// User name of the docker registry
	Username string `json:"username,omitempty" bson:"username,omitempty"`
}
