/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// If this field is set, the guest will be customized using Sysprep. At the very least, unattend_xml should be provided.
type GuestCustomizationStatusSysprep struct {

	// Whether the guest will be freshly installed using this unattend configuration, or whether this unattend configuration will be applied to a pre-prepared image. Default is \"PREPARED\".
	InstallType string `json:"install_type,omitempty" bson:"install_type,omitempty"`

	// This field contains a Sysprep unattend xml definition, as a string. The value must be base64 encoded.
	UnattendXml string `json:"unattend_xml,omitempty" bson:"unattend_xml,omitempty"`
}
