/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Host resources.
type HostDefStatusResources struct {
	Block Block `json:"block,omitempty" bson:"block,omitempty"`

	ControllerVm ControllerVm `json:"controller_vm,omitempty" bson:"controller_vm,omitempty"`

	// Host CPU capacity.
	CpuCapacityHz int64 `json:"cpu_capacity_hz,omitempty" bson:"cpu_capacity_hz,omitempty"`

	// Host CPU model.
	CpuModel string `json:"cpu_model,omitempty" bson:"cpu_model,omitempty"`

	FailoverCluster FailoverCluster `json:"failover_cluster,omitempty" bson:"failover_cluster,omitempty"`

	// List of GPUs on the host.
	GpuList []HostGpu `json:"gpu_list,omitempty" bson:"gpu_list,omitempty"`

	HostDisksReferenceList []DiskReference `json:"host_disks_reference_list,omitempty" bson:"host_disks_reference_list,omitempty"`

	// Host NICs.
	HostNicsIdList []string `json:"host_nics_id_list,omitempty" bson:"host_nics_id_list,omitempty"`

	Hypervisor Hypervisor `json:"hypervisor,omitempty" bson:"hypervisor,omitempty"`

	Ipmi Ipmi `json:"ipmi,omitempty" bson:"ipmi,omitempty"`

	// Host memory capacity in MiB.
	MemoryCapacityMib int64 `json:"memory_capacity_mib,omitempty" bson:"memory_capacity_mib,omitempty"`

	// Host monitoring status.
	MonitoringState string `json:"monitoring_state,omitempty" bson:"monitoring_state,omitempty"`

	// Number of CPU cores on Host.
	NumCpuCores int64 `json:"num_cpu_cores,omitempty" bson:"num_cpu_cores,omitempty"`

	// Number of CPU sockets.
	NumCpuSockets int64 `json:"num_cpu_sockets,omitempty" bson:"num_cpu_sockets,omitempty"`

	// Node serial number.
	SerialNumber string `json:"serial_number,omitempty" bson:"serial_number,omitempty"`

	WindowsDomain WindowsDomain `json:"windows_domain,omitempty" bson:"windows_domain,omitempty"`
}
