/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Host GPU.
type HostGpu struct {

	// The device ID of the GPU.
	DeviceId int64 `json:"device_id,omitempty" bson:"device_id,omitempty"`

	// The type of this GPU.
	Mode string `json:"mode,omitempty" bson:"mode,omitempty"`

	// Name of the host GPU.
	Name string `json:"name,omitempty" bson:"name,omitempty"`

	// NUMA node this GPU belongs to.
	NumaNode int64 `json:"numa_node,omitempty" bson:"numa_node,omitempty"`

	// GPU {segment:bus:device:function} (sbdf) address.
	PciAddress string `json:"pci_address,omitempty" bson:"pci_address,omitempty"`

	// Current status of the physical GPU.
	Status string `json:"status,omitempty" bson:"status,omitempty"`

	// The vendor of the GPU.
	Vendor string `json:"vendor,omitempty" bson:"vendor,omitempty"`
}
