/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Network Configuration for PC VM.
type NetworkConfig struct {

	// Gateway IP address.
	DefaultGateway string `json:"default_gateway,omitempty" bson:"default_gateway,omitempty"`

	// Network name. For AHV this field should be network name and for ESX this field should be port group.
	NetworkName string `json:"network_name,omitempty" bson:"network_name,omitempty"`

	// Network UUID.
	NetworkUuid string `json:"network_uuid,omitempty" bson:"network_uuid,omitempty"`

	// Subnet mask IP address.
	SubnetMask string `json:"subnet_mask,omitempty" bson:"subnet_mask,omitempty"`
}
