/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Prism central VM configuration.
type PcVm struct {

	// Container name.
	ContainerName string `json:"container_name,omitempty" bson:"container_name,omitempty"`

	// Data disk size in Mib.
	DataDiskSizeMib int64 `json:"data_disk_size_mib,omitempty" bson:"data_disk_size_mib,omitempty"`

	// Array of DNS IP addresses.
	DnsIpList []string `json:"dns_ip_list,omitempty" bson:"dns_ip_list,omitempty"`

	// Memory in Mib.
	MemorySizeMib int64 `json:"memory_size_mib,omitempty" bson:"memory_size_mib,omitempty"`

	NicList []PcVmNicConfiguration `json:"nic_list,omitempty" bson:"nic_list,omitempty"`

	// Number of sockets allocated per VM.
	NumSockets int64 `json:"num_sockets,omitempty" bson:"num_sockets,omitempty"`

	// VM name.
	VmName string `json:"vm_name,omitempty" bson:"vm_name,omitempty"`

	VmSize string `json:"vm_size,omitempty" bson:"vm_size,omitempty"`
}
