/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Prism central resources.
type PrismCentralResource struct {
	PcVmList []PcVm `json:"pc_vm_list,omitempty" bson:"pc_vm_list,omitempty"`

	// Indicates if the new prism central should be automatically register to the cluster.
	ShouldAutoRegister bool `json:"should_auto_register,omitempty" bson:"should_auto_register,omitempty"`

	// The desired version of Prism Central.
	Version string `json:"version,omitempty" bson:"version,omitempty"`

	// The desired virtual IP address of Prism Central cluster.
	VirtualIp string `json:"virtual_ip,omitempty" bson:"virtual_ip,omitempty"`
}
