/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

type ProjectDefStatusResources struct {

	// Optional default subnet if one is specified
	DefaultSubnetReference SubnetReference `json:"default_subnet_reference,omitempty" bson:"default_subnet_reference,omitempty"`

	// List of directory service group's information. Those groups are not managed by Nutanix.
	ExternalUserGroupList []UserGroup `json:"external_user_group_list,omitempty" bson:"external_user_group_list,omitempty"`

	ResourceDomain ResourceDomainResourcesStatus `json:"resource_domain,omitempty" bson:"resource_domain,omitempty"`

	// The role assigned to project users
	RoleReference RoleReference `json:"role_reference,omitempty" bson:"role_reference,omitempty"`

	// List of subnets for the project.
	SubnetReferenceList []SubnetReference `json:"subnet_reference_list,omitempty" bson:"subnet_reference_list,omitempty"`

	// List of users in the project including all the users from the users group if provided.
	UserReferenceList []UserReference `json:"user_reference_list,omitempty" bson:"user_reference_list,omitempty"`
}
