/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

type UserDefStatusResources struct {

	// Directory service reference if the user type is directory service.
	DirectoryServiceReference DirectoryServiceReference `json:"directory_service_reference,omitempty" bson:"directory_service_reference,omitempty"`

	// User's display name(common name) from the directory service.
	DisplayName string `json:"display_name,omitempty" bson:"display_name,omitempty"`

	// List of project references.
	ProjectsReferenceList []ProjectReference `json:"projects_reference_list,omitempty" bson:"projects_reference_list,omitempty"`

	// List of role references.
	RoleReferenceList []RoleReference `json:"role_reference_list,omitempty" bson:"role_reference_list,omitempty"`

	UsageSummary UserDefStatusResourcesUsageSummary `json:"usage_summary,omitempty" bson:"usage_summary,omitempty"`

	// UserPrincipalName of the user in the directory service.
	UserPrincipalName string `json:"user_principal_name,omitempty" bson:"user_principal_name,omitempty"`

	UserType string `json:"user_type,omitempty" bson:"user_type,omitempty"`
}
