/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// VirtualMachine Disk (VM Disk).
type VmDisk struct {
	DataSourceReference Reference `json:"data_source_reference,omitempty" bson:"data_source_reference,omitempty"`

	DeviceProperties VmDiskDeviceProperties `json:"device_properties,omitempty" bson:"device_properties,omitempty"`

	// Size for the disk in MiB.
	DiskSizeMib int64 `json:"disk_size_mib,omitempty" bson:"disk_size_mib,omitempty"`
}
