/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// The input object that defines a vm snapshot
type VmSnapshot struct {

	// Name of the snapshot
	Name string `json:"name,omitempty" bson:"name,omitempty"`

	Resources VmSnapshotResources `json:"resources,omitempty" bson:"resources,omitempty"`

	// Snapshot application consistency property
	SnapshotType string `json:"snapshot_type,omitempty" bson:"snapshot_type,omitempty"`
}
