/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// The output object that defines a vm snapshot
type VmSnapshotDefStatus struct {

	// Any error messages for the vm, if in an error state.
	MessageList []MessageResource `json:"message_list,omitempty" bson:"message_list,omitempty"`

	// Name of the snapshot.
	Name string `json:"name,omitempty" bson:"name,omitempty"`

	Resources VmSnapshotResources `json:"resources,omitempty" bson:"resources,omitempty"`

	// Describes the files that are included in the snapshot.
	SnapshotFileList []VmSnapshotDefStatusSnapshotFileList `json:"snapshot_file_list,omitempty" bson:"snapshot_file_list,omitempty"`

	// The consistency level desired while creating the snapshot.
	SnapshotType string `json:"snapshot_type,omitempty" bson:"snapshot_type,omitempty"`

	// The state of the vm entity.
	State string `json:"state,omitempty" bson:"state,omitempty"`
}
