/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// The status of a REST API call. Only used when there is a failure to report.
type VmSnapshotStatus struct {
	ApiVersion string `json:"api_version,omitempty" bson:"api_version,omitempty"`

	// The HTTP error code
	Code int64 `json:"code,omitempty" bson:"code,omitempty"`

	// Custom key-value details relevant to the status
	Details map[string]string `json:"details,omitempty" bson:"details,omitempty"`

	// The kind snapshot name
	Kind string `json:"kind,omitempty" bson:"kind,omitempty"`

	// The reason for the status
	Message string `json:"message,omitempty" bson:"message,omitempty"`

	// One snake_case word
	Reason string `json:"reason,omitempty" bson:"reason,omitempty"`

	// The only value possible is \"failure\"
	Status string `json:"status,omitempty" bson:"status,omitempty"`
}
