/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Volume disk configuration.
type VolumeDiskResource struct {

	// Volume group index of the disk.
	Index int64 `json:"index,omitempty" bson:"index,omitempty"`

	// NFS path of the image. For creating/updating operations. If NFS path is specified, then the operation would be clone and vmdisk_uuid should not be set.
	NfsPath string `json:"nfs_path,omitempty" bson:"nfs_path,omitempty"`

	// Size of the disk in MiB.
	SizeMib int64 `json:"size_mib,omitempty" bson:"size_mib,omitempty"`

	// Container UUID on which to create the disk.
	StorageContainerUuid string `json:"storage_container_uuid,omitempty" bson:"storage_container_uuid,omitempty"`

	// UUID of the vmdisk. For creating/updating operation, this will be the UUID of the disk to clone from. If UUID is specified, then the operation would be clone and nfs_path should not be set.
	VmdiskUuid string `json:"vmdisk_uuid,omitempty" bson:"vmdisk_uuid,omitempty"`
}
