/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Volume group resources.
type VolumeGroupResources struct {

	// VMs attached to volume group.
	AttachmentList []AttachmentReference `json:"attachment_list,omitempty" bson:"attachment_list,omitempty"`

	// Volume group disk specification.
	DiskList []VolumeDiskResource `json:"disk_list,omitempty" bson:"disk_list,omitempty"`

	// File system to be used for volume
	FileSystemType string `json:"file_system_type,omitempty" bson:"file_system_type,omitempty"`

	// iSCSI target full name
	IscsiTargetName string `json:"iscsi_target_name,omitempty" bson:"iscsi_target_name,omitempty"`

	// iSCSI target prefix-name.
	IscsiTargetPrefix string `json:"iscsi_target_prefix,omitempty" bson:"iscsi_target_prefix,omitempty"`

	// Whether the volume group can be shared across multiple iSCSI initiators.
	SharingStatus string `json:"sharing_status,omitempty" bson:"sharing_status,omitempty"`

	// The total size of the Volume Group.
	SizeMib int64 `json:"size_mib,omitempty" bson:"size_mib,omitempty"`
}
