/*
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine
 *
 * OpenAPI spec version: 3.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nutanix

// Hyper-V node domain.
type WindowsDomain struct {
	DomainCredential Credentials `json:"domain_credential,omitempty" bson:"domain_credential,omitempty"`

	// Full name of domain.
	DomainName string `json:"domain_name,omitempty" bson:"domain_name,omitempty"`

	// The name of the node to be renamed to during domain-join. If not given, a new name will be automatically assigned.
	Name string `json:"name,omitempty" bson:"name,omitempty"`

	// The name prefix in the domain in case of CPS deployment.
	NamePrefix string `json:"name_prefix,omitempty" bson:"name_prefix,omitempty"`

	// The ip of name server that can resolve the domain name. Required during joining domain.
	NameServerIp string `json:"name_server_ip,omitempty" bson:"name_server_ip,omitempty"`

	// Path to organization unit in the domain.
	OrganizationUnitPath string `json:"organization_unit_path,omitempty" bson:"organization_unit_path,omitempty"`
}
